### ISSUE TITLE
Couldn't get my query params from url on IOS side.

### ISSUE THREAD

**Issue by Abdusamad98** [llfbandit/app_links#137]
I have implemented App Links for both Android and IOS. Android side is working fine. But when it comes to ios I could not get my query params. 

In my apple-app-site-association file I wrote this lines of json

{
  "applinks": {
    "details": [
      {
        "appIDs": [
          "TEAM_ID_1.pro.example.app",
          "TEAM_ID_1.pro.example.app",
        ],
        "components": [
          {
            "?": "page=?*"
          }
        ]
      }
    ]
  }
}

In my url I am pressing this URL "https://app.exampl.pro?page=history". When I press the link in Android device I can get the query params. For IOS side I can't.

I read the instructions and implemented as it described

**Comment by llfbandit** [comment]
Your association file (AASA) feels wrong.

Here are few resources to help you.
https://developer.apple.com/documentation/xcode/supporting-associated-domains#Add-the-associated-domain-file-to-your-website

https://developer.apple.com/documentation/technotes/tn3155-debugging-universal-links

Closing this because not related to the package.
