### ISSUE TITLE
Deep links always open in app and system browser using Flutter 3.24.3

### ISSUE THREAD

**Issue by noforeignland** [llfbandit/app_links#158]
**Describe the bug**

After upgrading to Flutter 3.24.2 deep links on iOS open in both my app and the system browser.

Observed behaviour:
Click on universal link opens the app. Quickly after that the native browser is opened with the link as target. 

In my logs I see a warning "Failed to handle route information in Flutter.".

The warning points my to this Flutter PR which was recently merged and is part of 3.24.2: https://github.com/flutter/engine/pull/52643

See line 1885 of [FlutterViewController](https://api.flutter.dev/ios-embedder/_flutter_view_controller_8mm_source.html) where the warning is issued. My guess is that app_link does not return a success code here and that the framework passes the link on to the system browser to open instead.

**Does it related to**

[X] Universal Links (iOS)  

**Does the example project work?**

[X] Irrelevant here

**Did you fully read the instructions for the targeted platform before submitting this issue?**

[X] Yes  

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[X] Yes

**Comment by llfbandit** [comment]
Duplicates #156.
Please refer to Android & iOS docs to disable Flutter deeplinking.

**Comment by llfbandit** [comment]
Sure please fill a PR

**Comment by avneesh-sharma-mobile** [comment]
I am facing the same issue. After adding the following line of code and uploading the build to TestFlight, I installed it from TestFlight and tested the build. However, when I click on the Universal Link, it opens only in Safari instead of the app.

<key>FlutterDeepLinkingEnabled</key>
<false/>

i am using flutter version is 3.24.1 .
	
Please suggest what I might be missing in my code.
