### ISSUE TITLE
getInitialAppLinkString always get null when application starts

### ISSUE THREAD

**Issue by nathanael540** [llfbandit/app_links#25]
[android]
I'm having trouble getting the app link when the app is closed and a link is clicked in the browser.

the application opens, but the initial string is always null.

Its my code on main()

AppLinks links = AppLinks();
  String? initialLink = await links.getInitialAppLinkString();
  if (initialLink != null) {
    DeepLinksController().handleLink(initialLink);
  }
  links.stringLinkStream.listen((url) {
    DeepLinksController().handleLink(url);
  });

**Comment by UnluckyY1** [comment]
I am having the same issue did any one found a fix for that ?

**Comment by ShahinRockstarsIT** [comment]
Same issue, `appLinks.getInitialAppLink()` always returns null?

**Comment by nathanael540** [comment]
Unfortunately I can't solve this problem yet.

**Comment by llfbandit** [comment]
If you try to get initial link in your main method, so around calling runApp method, it won't work since the plugin is not attached to the engine.

You must call it in a widget like shown in the example.

If it still does not work, please fill a simple reproducer for investigation, otherwise this issue will be close soon.
